# Generated by Django 5.1.2 on 2024-12-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumbler', '0002_alter_tumbler_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumbler',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
