# Generated by Django 5.1.2 on 2024-12-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumbler', '0003_tumbler_is_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tumbler',
            name='is_promo',
        ),
        migrations.AddField(
            model_name='tumbler',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
