# Generated by Django 5.1.2 on 2024-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumbler', '0005_tumbler_is_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumbler',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
