# Generated by Django 5.1.2 on 2024-12-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumbler', '0006_tumbler_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
