# Generated by Django 5.1.2 on 2024-12-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumbler', '0007_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='discount_percentage',
        ),
    ]
