# Generated by Django 5.1.2 on 2024-12-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumbler', '0008_remove_promo_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
